language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 4e0235eb-28b7-4735-96a5-dd0874fa452f
  app: infinite-garden-26914
  on:
    repo: preston206/lake-washington-gig-finder
notifications:
  email:
    on_success: never
    on_failure: never